spring:
  application:
    name: smartfleet

  datasource:
    url: jdbc:mysql://127.0.0.1:3306/smartfleet
    username: database_username
    password: database_password
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false

  data:
    redis:
      host: localhost
      port: redis_port:6379

  Kafka:
    bootstrap-servers: localhost:9092

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

    consumer:
      group-id: smartfleet-order-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: com.smartfleet.smartfleet.kafka


server:
  port: 8080